# Generated by Django 5.0.6 on 2024-05-15 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_std_type_student_type_alter_sponsor_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contract_amount',
            new_name='contract',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='dt',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 16, 23, 27, 341610)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dt',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 16, 23, 27, 342607)),
        ),
    ]
